apiVersion: v1
kind: Pod
metadata:
  name: pod-transform
spec:
  terminationGracePeriodSeconds: 2
  containers:
    - name: transform
      image: transform:v1
      command:
        ["sh", "-c", "sqlite3 /transform/transform.sqlite < transform.sql"]
      volumeMounts:
        - name: pv-extract
          mountPath: /extract
        - name: pv-transform
          mountPath: /transform
  restartPolicy: Never
  volumes:
    - name: pv-extract
      persistentVolumeClaim:
        claimName: pvc-extract
    - name: pv-transform
      persistentVolumeClaim:
        claimName: pvc-transform
